version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    tty: true
    ports:
      - 5678:5679    # note port remapping
      - 15678:15679  # note port remapping
    networks:
      - petricnet

  pypi-service:
    image: petrichor-pypi-service
    container_name: pypi-server
    build: ./services/pypi-service/
    restart: always
    ports:
      - 8081:8081
    networks:
      - petricnet
    depends_on:
    - "rabbitmq"

  api:
    image: petrichor-weather-service
    build: ./services/weather-service/
    env_file:
      - ./services/weather-service/environ.env
    tty: true
    depends_on:
      - "pypi-service"
      - "rabbitmq"
    ports:
      - 5000:5000
    networks:
      - petricnet

  log-service:
    image: petrichorlog-service
    build: ./services/log-service/
    tty: true
    ports:
      - 3000:3000
    networks:
      - petricnet
    depends_on:
      - "rabbitmq"

networks:
  petricnet:
    driver: bridge
