version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    tty: true
    ports:
      - 5672:5672
      - 15672:15672

  pypi-service:
    image: petrichor-pypi-service
    container_name: pypi-server
    build: ./services/pypi-service/
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq

  weather-service:
    image: petrichor-weather-service
    build: ./services/weather-service/
    env_file:
      - ./services/weather-service/environ.env
    tty: true
    depends_on:
      - pypi-service
      - rabbitmq

  log-service:
    image: petrichor-log-service
    build: ./services/log-service/
    tty: true
    depends_on:
      - pypi-service
      - rabbitmq

  web:
    image: petrichor-web
    build: ./services/web/petrichor/
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
