version: '3.7'

services:
  postgres:
    image: postgres
    env_file:
    - ./docker-postgres/environ_vars.env
    build:
      context: ./docker-postgres
    restart: always
    ports:
    - '127.0.0.1:5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  rabbitmq:
    image: rabbitmq:3.7-management
    tty: true
    ports:
      - 5673:5672
      - 15673:15672

  pypi-service:
    image: petrichor-pypi-service
    container_name: pypi-server
    build: ./services/pypi-service/
    restart: always
    ports:
    - 8081:8081
    depends_on:
    - rabbitmq

  weather-service:
    image: petrichor-weather-service
    build: ./services/weather-service/
    env_file:
    - ./services/weather-service/environ_vars.env
    tty: true
    depends_on:
    - pypi-service
    - postgres
    - rabbitmq

  log-service:
    image: petrichor-log-service
    build: ./services/log-service/
    tty: true
    env_file:
    - ./services/log-service/environ_vars.env
    depends_on:
    - pypi-service
    - postgres
    - rabbitmq

  web:
    image: petrichor-web
    build: ./services/web/petrichor/
    ports:
    - 3000:3000
    depends_on:
    - rabbitmq
    - postgres
